### ISSUE TITLE
Feature request: Add action to append annotations

### ISSUE THREAD

**Issue by SkySonR** [stakater/Chowkidar#31]
It would be very useful to store information about annotations for different k8s operators/controllers inside configmaps. 
I do not want to care about manual specification of annotation for each deployment/helm chart. I want to have a cluster policy. This is useful for any k8s operator or k8s controller. 
As example, cloud specific annotations for ALB in AWS/Azure. Also it would be useful to add reloader.stakater.com/auto: "true" annotation for some type k8s resources.

**Comment by ahmadiq** [comment]
> It would be very useful to store information about annotations for different k8s operators/controllers inside configmaps.
> I do not want to care about manual specification of annotation for each deployment/helm chart. I want to have a cluster policy. This is useful for any k8s operator or k8s controller.
Interesting. Do you know of any examples of this architecture.

> Also it would be useful to add reloader.stakater.com/auto: "true" annotation for some type k8s resources.
Can you clarify and explain further what you mean by this

**Comment by SkySonR** [comment]
> Can you clarify and explain further what you mean by this
I mean that to use Reloader we need to add reloader.stakater.com/auto: "true" annotation. By this feature we can specify that all deployments which has been deployed to cluster will be visiable by Reloader.

> Interesting. Do you know of any examples of this architecture.

I just seached somesthing and yours project looks ideal for this case. 
My particular case:
I need to add external-dns.alpha.kubernetes.io/target annotation to each Ingress object which would be created in the cluster. 

It would be like
type | The type of Resource you want to monitor, like Pods, Deployments, etc
watchcriterion | The criterion for which you want to take actions for the controller e.g. ResourceExists,etc
actions | **Insert annotation list to Pods, Deployments, etc**
